-- =========================================
-- Database Setup for Reward App
-- =========================================

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS `reward_app` 
DEFAULT CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

-- Use the database
USE `reward_app`;

-- =========================================
-- Table: admins
-- =========================================
CREATE TABLE IF NOT EXISTS `admins` (
  `id` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  
  PRIMARY KEY (`id`),
  UNIQUE KEY `admins_email_unique` (`email`),
  INDEX `idx_admins_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================
-- Sample Admin Data (Optional)
-- Password: Admin123! (hashed with bcrypt)
-- =========================================
-- Uncomment the line below to insert sample admin
-- Note: You should run the seed.ts instead for proper password hashing

-- INSERT INTO `admins` (`id`, `email`, `password`, `name`, `createdAt`, `updatedAt`) 
-- VALUES (
--   'sample_admin_id_001',
--   'admin@reward.com',
--   '$2a$10$YourHashedPasswordHere',  -- This will be generated by seed.ts
--   'Administrator',
--   NOW(3),
--   NOW(3)
-- );

-- =========================================
-- Verify Table Creation
-- =========================================
SHOW TABLES;
DESCRIBE `admins`;
